DROP TABLE IF EXISTS note_labels CASCADE;

CREATE TABLE note_labels (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  handle VARCHAR(255) NOT NULL
);