DROP TABLE IF EXISTS note_labels_XREF CASCADE;

CREATE TABLE note_labels_XREF (
  id SERIAL PRIMARY KEY NOT NULL,
  note_id INTEGER REFERENCES notes(id) ON DELETE CASCADE,
  note_label_id INTEGER REFERENCES note_labels(id) ON DELETE CASCADE
);