DROP TABLE IF EXISTS navbar CASCADE;

CREATE TABLE navbar (
  id SERIAL PRIMARY KEY NOT NULL,
  display BOOLEAN NOT NULL,
  folded BOOLEAN NOT NULL,
  position VARCHAR(255) NOT NULL,
  style VARCHAR(255) NOT NULL
);