DROP TABLE IF EXISTS settings CASCADE;

CREATE TABLE themes (
  id SERIAL PRIMARY KEY NOT NULL,
  main VARCHAR(255) NOT NULL,
  navbar VARCHAR(255) NOT NULL,
  toolbar VARCHAR(255) NOT NULL,
  footer VARCHAR(255) NOT NULL
);