DROP TABLE IF EXISTS starredContacts CASCADE;

CREATE TABLE starredContacts (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  contact_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);