DROP TABLE IF EXISTS activities CASCADE;

CREATE TABLE activities (
  id SERIAL PRIMARY KEY NOT NULL,
  card_id INTEGER REFERENCES cards(id) ON DELETE CASCADE,
  type VARCHAR(255) NOT NULL,
  member_id INTEGER NOT NULL,
  message VARCHAR(255) NOT NULL,
  time TIMESTAMP NOT NULL
);