DROP TABLE IF EXISTS attachments CASCADE;

CREATE TABLE attachments (
  id SERIAL PRIMARY KEY NOT NULL,
  card_id INTEGER REFERENCES cards(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  src TEXT NOT NULL,
  time TIMESTAMP NOT NULL,
  type VARCHAR(255) NOT NULL
);