DROP TABLE IF EXISTS board_labels CASCADE;

CREATE TABLE board_labels (
  id SERIAL PRIMARY KEY NOT NULL,
  board_id INTEGER REFERENCES boards(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  class VARCHAR(255) NOT NULL
);